### ISSUE TITLE
ahs's todo

### ISSUE THREAD

**Issue by ashhhleyyy** [alyxbb/eng1-part1#64]
- [x] check website deploy
- [x] upload jar to backblaze
- [x] license links
- [x] make code zip
